version: "3"
services:
  server:
    image: chipmunkdev/hamkke-server
    container_name: hamkke_node
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      MYSQL_HOST: hamkke-server
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 66356635
      MYSQL_DATABASE: hamkke
      MYSQL_PORT: 3306
    mem_limit: 128m
    
