version: "3"
services:
  server:
    container_name: hamkke_node
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
